image: docker:latest

services:
  - docker:dind 

variables:
  DOCKER_DRIVER: overlay2
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

before_script:
  - docker info
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

stages:
  - build
  - test
  - deploy

.default_rules:
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"

build:
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE

test:
  stage: test
  script:
    - docker run --rm $CI_REGISTRY_IMAGE mvn test

deploy:
  stage: deploy
  script:
    - docker-compose run -e INPUT_DATA=0 app