image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

stages:
  - build
  - test
  - package

before_script:
  - apk add maven

.default_rules:
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"

build-job:
  stage: build
  tags:
    - docker
  script:
    - echo "Build job started..."
    - mvn compile

test-job:
  stage: test
  tags:
    - docker
  script:
    - echo "Test job started..."
    - mvn test

package-job:
  stage: package
  tags:
    - docker
  script:
    - echo "Package job started..."
    - mvn package
