version: '3'

services:
  postgresqldb:
    image: postgres:15.3
    environment:
      POSTGRES_USER: serhii
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: school
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgresqldb
