name: Java CI/CD with Maven and Docker

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master]

jobs:
  build-test-package-deploy:
    strategy:
      matrix:
        job: ['build', 'test', 'package', 'deploy']
        include:
          - job: 'build'
            run: 'mvn -B compile'
          - job: 'test'
            run: 'mvn -B test'
          - job: 'package'
            run: 'mvn -B package'
          - job: 'deploy'
            run: 'docker compose up -d'
            setup: 'docker/setup-buildx-action@v1'
    needs: ${{ matrix.job == 'build' && '' || 'build-test-package-deploy' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Set up Docker
      if: matrix.setup
      uses: ${{ matrix.setup }}
    - name: ${{ matrix.job }} with Maven
      run: ${{ matrix.run }}
